application: seleniumbeginnersguide-hrd
version: 1
runtime: python
api_version: 1

handlers:
- url: /styles
  static_dir: styles

- url: /scripts
  static_dir: scripts

- url: .*
  script: main.py

- url: /static/(.*\.appcache)
  static_files: static/\1
  mime_type: text/cache-manifest
  upload: static/(.*\.appcache)
